apiVersion: v1
kind: Service
metadata:
  name: {{ include "ServicesAPI.fullname" . }}
  labels:
    {{- include "ServicesAPI.labels" . | nindent 4 -}}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $index, $port := .Values.pizzaToppings -}}
    - port: {{ $port.port }}
      targetPort: {{ $index }}
      protocol: TCP
      name: {{ default $index $port.name }}
    {{- end -}}
  selector:
    {{- include "ServicesAPI.selectorLabels" . | nindent 4 -}}
