{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ServicesAPI.fullname" . }}
  labels:
    {{- include "ServicesAPI.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ServicesAPI.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.target.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: {{ .Values.autoscaling.target.cpu.type }}
          averageUtilization: {{ .Values.autoscaling.target.cpu.percentage }}
    {{- end }}
    {{- if .Values.autoscaling.target.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: {{ .Values.autoscaling.target.memory.type }}
          averageUtilization: {{ .Values.autoscaling.target.memory.percentage }}
    {{- end }}
{{- end }}